### ISSUE TITLE
Feature Request - Gray background (or configureable)

### ISSUE THREAD

**Issue by shazzap** [jscher2000/Show-History-Frequent-Sites-button-extension#2]
Hi there,

I've found this addon to be quite nice and very useful, even more so in a post-Firefiox 77 world which Mozilla changed Firefox's address bar behavior.

This is admittedly a superficial request, but would it be possible to introduce a 3rd color scheme? I use a dark gray browser theme and the addon's default white background is somewhat glaring when superimposed on the rest of the browser. Conversely, the black background is also rather hard on the eyes.

A 3rd, gray theme would be nice.; or even better, the ability to specify the background and foreground colors as hex codes..

Regardless, thanks for the addon, much appreciated :)

**Comment by jscher2000** [comment]
Well, you forced me to review the disorganized way I've assigned different theme colors and streamline that enough to provide this new feature. Version 1.3 will have two form fields for you to assign your own colors using the syntax of your choice. Invalid colors should just be ignored by the browser, so hopefully there's not a huge risk of breakage.

![advanced-color-tweaking-bad-color](https://user-images.githubusercontent.com/8264646/86544024-8a41c180-bed8-11ea-8c71-87d6fe60f029.png)

**Comment by shazzap** [comment]
Thank you. Much easier on the eyes (well my old eyes, at least). I may attempt a little tweaking of it to play with some padding and the borders for my own benefit.

I think I may have encountered a couple other issues (unrelated to this) regarding launching tabs, But need to first test and verify whether its related or not to containers or other addons I'm running.
