### ISSUE TITLE
Middle click opens two tabs

### ISSUE THREAD

**Issue by Apexii** [jscher2000/Show-History-Frequent-Sites-button-extension#3]
Don't really know if it's intended or not, but Middle clicking on the URL opens the tab twice as opposed to Middle clicking on the title where it only opens the tab once.

**Comment by jscher2000** [comment]
Thanks, I hadn't noticed that. I found a way to fix it and will include that in the next update.

**Comment by jscher2000** [comment]
This should be fixed in version 1.3. There is a minor difference in behavior because middle-clicking the link opens the new tab adjacent to the current tab, while middle-clicking the title opens the new tab at the end of the bar.

**Comment by Apexii** [comment]
Awesome, looking forward to it.
