### ISSUE TITLE
Request: Unlimited Height

### ISSUE THREAD

**Issue by Copyrites** [jscher2000/Show-History-Frequent-Sites-button-extension#4]
Is there an underlying system limitation that requires the height of the drop-down be limited to 600px?  I'd like to be able to see as much of my history as will fit on my screen without having to use a scrollbar.  Is that possible?

Thanks

**Comment by jscher2000** [comment]
That limit applies to all extension drop-downs -- you can use style rule hacks to enlarge the actual drop-down, but the content within it stays the same size. So far, no one provided a solution in response to my request here, but maybe there's an answer out on the web somewhere:

https://www.reddit.com/r/FirefoxCSS/comments/hbr7xx/any_way_to_enlarge_extension_popup_beyond_800x600/

**Comment by jscher2000** [comment]
I haven't heard of a solution to this, so reluctantly, I'm going to close this issue.
