### ISSUE TITLE
Errors in Firefox 111.0.1

### ISSUE THREAD

**Issue by ilyagoz** [jscher2000/Show-History-Frequent-Sites-button-extension#8]
![2023-03-27 12-38-28 Скриншот экрана](https://user-images.githubusercontent.com/95026488/227850191-d164b874-39df-4e95-86c1-925a92cad7b2.png)

**Comment by jscher2000** [comment]
I don't know why the add-on is not able to use storage on your Firefox. If a normal restart of Firefox doesn't resolve it, you could try removing the existing storage data for the add-on in case that somehow became corrupted.

To remove the storage data for the add-on:

(1) Type or paste the following URL into the address bar and press Enter/Return to load it:

about:debugging#/runtime/this-firefox

(2) Scroll down to this add-on and click its "Inspect" button to pop up a debugging window.

(3) Change to the Storage tab and expand the Extension Storage section in the left column and click the extension ID (this is unique for each installation, so yours will be different than in the screenshot below.

![Fx111-show-history-about-debugging-storage-context](https://user-images.githubusercontent.com/8264646/227994383-cd068fed-708e-4abf-aa91-850ed2c8c963.png)

(4) Right-click the "prefs" key and delete it. (Note: this key might not exist in a new installation, it might only be created once you customize some settings for the add-on.)

Any improvement?

**Comment by ilyagoz** [comment]
Thank you! I was able to fix the error by setting dom.quotaManager.useDOSDevicePathSyntax=false in about:config, per advice here: https://www.reddit.com/r/firefox/comments/gzu864/comment/ftihhm9/
With dom.quotaManager.useDOSDevicePathSyntax=true even "Inspect" does not work, so it is probably browsers fault.
